-- Week08
-- 각 학년의 학점별로 평균 점수 검색
SELECT S.GRADE "학년", H.GRADE "성적", ROUND(AVG(TOTAL), 2) "각 학년의 학점 별 평균 점수"
FROM STUDENT S, SCORE O, HAKJUM H
WHERE S.STUDNO = O.STUDNO AND O.TOTAL BETWEEN H.MIN_POINT AND H.MAX_POINT
GROUP BY S.GRADE, H.GRADE
ORDER BY 1, 2;

-- 각 학년의 학점별로 평균 점수 검색 - ANSI JOIN 방식
SELECT S.GRADE "학년", H.GRADE "성적", ROUND(AVG(TOTAL), 2) "각 학년의 학점 별 평균 점수"
FROM STUDENT S JOIN SCORE O
ON S.STUDNO = O.STUDNO
JOIN HAKJUM H
ON O.TOTAL BETWEEN H.MIN_POINT AND H.MAX_POINT
GROUP BY S.GRADE, H.GRADE
ORDER BY 1, 2;

-- EMP 테이블 - 30번 부서의 사원들끼리 급여를 비교하여, 자신의 급여보다 많이 받는 사람 검색
-- 자신의 이름, 부서번호, 급여, 검색된 사원의 이름, 부서번호, 급여 출력
SELECT A.ENAME, A.DEPTNO, A.SAL, B.ENAME, B.DEPTNO, B.SAL
FROM EMP A, EMP B
WHERE A.SAL < B.SAL(+) AND B.DEPTNO(+) = 30 AND A.DEPTNO = 30
ORDER BY 3 DESC, 1, 6 DESC;

-- ANSI JOIN 방식
SELECT A.ENAME, A.DEPTNO, A.SAL, B.ENAME, B.DEPTNO, B.SAL
FROM EMP A LEFT OUTER JOIN EMP B
ON A.SAL < B.SAL AND A.DEPTNO = B.DEPTNO
WHERE A.DEPTNO = 30
ORDER BY 3 DESC, 1, 6 DESC;

-- EMP 테이블 - 30번 부서의 사원들끼리 급여를 비교하여, 자신의 급여보다 많이 받는 사람 검색
-- 자신의 이름, 부서번호, 급여, 자신보다 급여를 많이 받는 사원수
SELECT A.ENAME, A.DEPTNO, A.SAL, COUNT(B.EMPNO) "자신보다 급여를 많이 받는 사원수"
FROM EMP A, EMP B
WHERE A.SAL < B.SAL(+) AND A.DEPTNO = B.DEPTNO(+) AND A.DEPTNO = 30
GROUP BY A.ENAME, A.DEPTNO, A.SAL
ORDER BY 3 DESC;

-- ANSI JOIN 방식
SELECT A.ENAME, A.DEPTNO, A.SAL, COUNT(B.EMPNO) "자신보다 급여를 많이 받는 사원수"
FROM EMP A LEFT OUTER JOIN EMP B
ON A.SAL < B.SAL AND A.DEPTNO = B.DEPTNO
WHERE A.DEPTNO = 30
GROUP BY A.ENAME, A.DEPTNO, A.SAL
ORDER BY 3 DESC;

-- 10장 서브 쿼리 429p - 단일행 서브쿼리 연습문제 1번
SELECT S.NAME "STUD_NAME", D.DNAME "DEPT_NAME"
FROM STUDENT S, DEPARTMENT D
WHERE S.DEPTNO1 = D.DEPTNO
AND S.DEPTNO1 = (SELECT DEPTNO1 FROM STUDENT WHERE NAME = 'Anthony Hopkins')
ORDER BY 1;

-- ANSI JOIN 방식
SELECT S.NAME "STUD_NAME", D.DNAME "DEPT_NAME"
FROM STUDENT S JOIN DEPARTMENT D
ON S.DEPTNO1 = D.DEPTNO
WHERE S.DEPTNO1 = (SELECT DEPTNO1 FROM STUDENT WHERE NAME = 'Anthony Hopkins')
ORDER BY 1;

-- 10장 서브 쿼리 429p - 단일행 서브쿼리 연습문제 2번
SELECT P.NAME "PROF_NAME",
    TO_CHAR(P.HIREDATE, 'YYYY-MM-DD') "HIREDATE",
    D.DNAME "DEPT_NAME"
FROM PROFESSOR P, DEPARTMENT D
WHERE P.DEPTNO = D.DEPTNO
AND P.HIREDATE > (SELECT HIREDATE
    FROM PROFESSOR
    WHERE NAME = 'Meg Ryan');

-- ANSI JOIN 방식
SELECT P.NAME "PROF_NAME",
    TO_CHAR(P.HIREDATE, 'YYYY-MM-DD') "HIREDATE",
    D.DNAME "DEPT_NAME"
FROM PROFESSOR P JOIN DEPARTMENT D
ON P.DEPTNO = D.DEPTNO
WHERE P.HIREDATE > (SELECT HIREDATE
    FROM PROFESSOR
    WHERE NAME = 'Meg Ryan');

-- 10장 서브 쿼리 429p - 단일행 서브쿼리 연습문제 3번
SELECT NAME, WEIGHT
FROM STUDENT
WHERE WEIGHT > (SELECT AVG(WEIGHT) FROM STUDENT WHERE DEPTNO1 = 201 GROUP BY DEPTNO1);

-- 10장 서브 쿼리 432p - 다중행 서브쿼리 예제 1번
SELECT EMPNO, NAME, DEPTNO
FROM EMP2
WHERE DEPTNO IN (SELECT DCODE FROM DEPT2 WHERE AREA = 'Pohang Main Office');

-- 10장 서브 쿼리 434p - 다중행 서브쿼리 연습문제 1번
SELECT NAME, POSITION, TO_CHAR(PAY, '$999,999,999') "SALARY"
FROM EMP2
WHERE PAY > ANY (SELECT PAY
    FROM EMP2
    WHERE POSITION = 'Section head')
ORDER BY 3 DESC;

SELECT NAME, POSITION, TO_CHAR(PAY, '$999,999,999') "SALARY"
FROM EMP2
WHERE PAY > (SELECT MIN(PAY)
    FROM EMP2
    WHERE POSITION = 'Section head'
    GROUP BY POSITION)
ORDER BY 3 DESC;

-- 10장 서브 쿼리 434p - 다중행 서브쿼리 연습문제 2번
SELECT NAME, GRADE, WEIGHT
FROM STUDENT
WHERE WEIGHT < ALL (SELECT WEIGHT
    FROM STUDENT
    WHERE GRADE = 2)
ORDER BY 1;

SELECT NAME, GRADE, WEIGHT
FROM STUDENT
WHERE WEIGHT < (SELECT MIN(WEIGHT)
    FROM STUDENT
    WHERE GRADE = 2
    GROUP BY GRADE)
ORDER BY 1;

-- 10장 서브 쿼리 435p - 다중행 서브쿼리 연습문제 3번
SELECT D.DNAME "DNAME", E.NAME "NAME", TO_CHAR(E.PAY, '$999,999,999')"SALARY"
FROM EMP2 E, DEPT2 D
WHERE E.DEPTNO = D.DCODE
AND E.PAY < (SELECT MIN(AVG(PAY))
    FROM EMP2
    GROUP BY DEPTNO)
ORDER BY 3;

SELECT D.DNAME "DNAME", E.NAME "NAME", TO_CHAR(E.PAY, '$999,999,999')"SALARY"
FROM EMP2 E, DEPT2 D
WHERE E.DEPTNO = D.DCODE
AND E.PAY < ALL (SELECT AVG(PAY)
    FROM EMP2
    GROUP BY DEPTNO)
ORDER BY 3;

-- ANSI JOIN 방식
SELECT D.DNAME "DNAME", E.NAME "NAME", TO_CHAR(E.PAY, '$999,999,999')"SALARY"
FROM EMP2 E JOIN DEPT2 D
ON E.DEPTNO = D.DCODE
WHERE E.PAY < (SELECT MIN(AVG(PAY))
    FROM EMP2
    GROUP BY DEPTNO)
ORDER BY 3;

-- 10장 서브 쿼리 435p - 다중 컬럼 서브쿼리 연습문제 1번
SELECT P.PROFNO "PROFNO",
    P.NAME "PROF_NAME",
    TO_CHAR(P.HIREDATE, 'YYYY-MM-DD') "HIREDATE",
    D.DNAME "DEPT_NAME"
FROM PROFESSOR P, DEPARTMENT D
WHERE P.DEPTNO = D.DEPTNO
AND (P.DEPTNO, P.HIREDATE) IN (SELECT DEPTNO, MIN(HIREDATE)
    FROM PROFESSOR
    GROUP BY DEPTNO)
ORDER BY 3;

-- ANSI JOIN 방식
SELECT P.PROFNO "PROFNO",
    P.NAME "PROF_NAME",
    TO_CHAR(P.HIREDATE, 'YYYY-MM-DD') "HIREDATE",
    D.DNAME "DEPT_NAME"
FROM PROFESSOR P JOIN DEPARTMENT D
ON P.DEPTNO = D.DEPTNO
WHERE (P.DEPTNO, P.HIREDATE) IN (SELECT DEPTNO, MIN(HIREDATE)
    FROM PROFESSOR
    GROUP BY DEPTNO)
ORDER BY 3;

-- 10장 서브 쿼리 435p - 다중 컬럼 서브쿼리 연습문제 2번
SELECT NAME, POSITION, TO_CHAR(PAY, '$999,999,999') "SALARY"
FROM EMP2
WHERE (POSITION, PAY) IN (SELECT POSITION, MAX(PAY)
    FROM EMP2
    GROUP BY POSITION)
ORDER BY 3;
