-- Week05
SELECT TRUNC(MONTHS_BETWEEN(SYSDATE, '01/12/25')/12) AS "년",
    TRUNC(MOD(MONTHS_BETWEEN(SYSDATE, '01/12/25'), 12)) AS "월",
    TRUNC(SYSDATE-ADD_MONTHS('01/12/25', MONTHS_BETWEEN(SYSDATE, '01/12/25')))+1 AS "일"
FROM DUAL;

SELECT TO_CHAR(TO_DATE(SUBSTR(JUMIN, 1, 6)), 'YY"년" MM"월" DD"일"') AS "생년월일"
FROM STUDENT;

SELECT NAME, DECODE(GRADE,3, DECODE(DEPTNO2, NULL, '복수전공 안 함', '복수전공') ,'타학년') "복수전공"
FROM STUDENT;

SELECT DECODE(SUBSTR(JUMIN,7,1), 2, DECODE(GRADE, 4, NAME, ''), ' ')
FROM STUDENT;

SELECT DECODE(GRADE, 4, DECODE(SUBSTR(JUMIN,7,1), 2, NAME, '남학생'), '타학년')
FROM STUDENT;

SELECT COUNT(*) "Student Num" FROM STUDENT;

SELECT COUNT(*) "Student Num" FROM STUDENT WHERE GRADE = 3;

SELECT COUNT(DISTINCT DEPTNO) FROM EMP;

SELECT COUNT(*) "전체 학생수", COUNT(DEPTNO2) "복수전공 학생수" FROM STUDENT;

SELECT MAX(LENGTH(NAME)) "Longest Name" FROM PROFESSOR;

SELECT NAME, MAX(LENGTH(NAME)) "Longest Name"
FROM PROFESSOR
GROUP BY NAME HAVING LENGTH(NAME) = MAX(LENGTH(NAME));

SELECT DEPTNO, JOB, COUNT(*)
FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY 1, 2;

SELECT DEPTNO, COUNT(*) "학과 별 소속 교수 인원수"
FROM PROFESSOR
GROUP BY DEPTNO
ORDER BY 1;

-- 연도 별 입사한 인원 수 - EMP 테이블
SELECT SUBSTR(HIREDATE, 1, 2) "입사 연도", COUNT(*) "연도 별 입사한 인원 수"
FROM EMP
GROUP BY SUBSTR(HIREDATE, 1, 2)
ORDER BY 1;

SELECT TO_CHAR(HIREDATE, 'YY"년"') "입사 연도", COUNT(*) "연도 별 입사한 인원 수"
FROM EMP
GROUP BY TO_CHAR(HIREDATE, 'YY"년"')
ORDER BY 1;

-- 3학년 학생 중에서 학과 별 인원 수 - STUDENT 테이블
SELECT DEPTNO1 "학과", COUNT(*)
FROM STUDENT
WHERE GRADE = 3
GROUP BY DEPTNO1
ORDER BY 1;

-- SELECT 절과 GROUP BY 절에 GRADE 를 추가하여 GRADE 를 표시해 줄 수도 있음.
-- WHERE 절에서 이미 3학년 조건을 걸러냈기 때문에 GROUP BY 절에 넣어도 그룹은 동일함.
SELECT DEPTNO1 "학과", COUNT(*), GRADE
FROM STUDENT
WHERE GRADE = 3
GROUP BY DEPTNO1, GRADE
ORDER BY 1;

-- 4학년 학생의 남성, 여성 별 인원 수 - STUDENT 테이블
SELECT DECODE(SUBSTR(JUMIN, 7, 1), 1, '남학생', '여학생') "성별", COUNT(*) || '명' "인원 수"
FROM STUDENT
WHERE GRADE = 4
GROUP BY DECODE(SUBSTR(JUMIN, 7, 1), 1, '남학생', '여학생')
ORDER BY 1;

-- 평균 키가 170 이상인 학년과 평균 키
SELECT GRADE "학년", AVG(HEIGHT) || 'cm' "평균 키"
FROM STUDENT
GROUP BY GRADE HAVING AVG(HEIGHT) >= 170
ORDER BY 1;

-- 2학년이면서, 같은 학과 학생수가 2명 이상인 학과 번호, 학생 수
SELECT DEPTNO1 "학과 번호", COUNT(*) || '명' "학생 수"
FROM STUDENT
WHERE GRADE = 2
GROUP BY DEPTNO1 HAVING COUNT(*) >= 2
ORDER BY 1;

SELECT DEPTNO, JOB, ROUND(AVG(SAL), 1) AVG_SAL, COUNT(*) CNT_EMP
FROM EMP
GROUP BY ROLLUP(DEPTNO, JOB);

SELECT DEPTNO, JOB, ROUND(AVG(SAL), 1) AVG_SAL, COUNT(*) CNT_EMP
FROM EMP
GROUP BY CUBE(DEPTNO, JOB);
