-- 1번 문제
SELECT SONG "노래"
FROM ALBUM A, TRACK T
WHERE A.ASIN = T.ALBUM AND A.TITLE = 'Blur';

-- 2번 문제
SELECT A.TITLE "타이틀", T.SONG "가장 긴 곡명"
FROM ALBUM A, TRACK T
WHERE A.ASIN = T.ALBUM
    AND (A.ASIN, LENGTH(T.SONG)) IN (SELECT T.ALBUM, MAX(LENGTH(T.SONG))
    	FROM TRACK T
    	GROUP BY T.ALBUM);

-- 3번 문제
SELECT A.TITLE "타이틀", COUNT(*) "Time 단어가 포함된 수록곡 개수"
FROM ALBUM A, TRACK T
WHERE A.ASIN = T.ALBUM AND T.SONG LIKE '%Time%'
GROUP BY T.ALBUM, A.TITLE;

-- 4번 문제
SELECT A.ASIN "앨범번호", A.TITLE "타이틀", T.SONG "동일한 곡명"
FROM ALBUM A, TRACK T
WHERE A.ASIN = T.ALBUM
    AND T.SONG IN (SELECT SONG
        FROM TRACK
        GROUP BY SONG HAVING COUNT(*) >= 2);

-- 5번 문제
SELECT TRUNC(MONTHS_BETWEEN(SYSDATE, '23/02/20')/12) "년",
    TRUNC(MOD(MONTHS_BETWEEN(SYSDATE, '23/02/20'), 12)) "월",
    TRUNC(SYSDATE-ADD_MONTHS('23/02/20', MONTHS_BETWEEN(SYSDATE, '23/02/20'))) "일"
FROM DUAL;

-- 6번 문제
SELECT EMPNO "사번", ENAME "이름", JOB "업무",
    DECODE(MOD(EMPNO, 2), 0, '백팀', '청팀') "TEAM"
FROM EMP
WHERE JOB <> 'PRESIDENT';
