-- 3장 연습문제 1번
SELECT MAX(SAL+NVL(COMM, 0)) "MAX",
    MIN(SAL+NVL(COMM, 0)) "MIN",
    ROUND(AVG(SAL+NVL(COMM, 0)), 1) "AVG"
FROM EMP;

-- 3장 연습문제 2번
SELECT COUNT(*) || 'EA' "TOTAL",
    COUNT(DECODE(SUBSTR(BIRTHDAY, 4, 2), '01', 0)) || 'EA' "JAN",
    COUNT(DECODE(SUBSTR(BIRTHDAY, 4, 2), '02', 0)) || 'EA' "FEB",
    COUNT(DECODE(SUBSTR(BIRTHDAY, 4, 2), '03', 0)) || 'EA' "MAR",
    COUNT(DECODE(SUBSTR(BIRTHDAY, 4, 2), '04', 0)) || 'EA' "APR",
    COUNT(DECODE(SUBSTR(BIRTHDAY, 4, 2), '05', 0)) || 'EA' "MAY",
    COUNT(DECODE(SUBSTR(BIRTHDAY, 4, 2), '06', 0)) || 'EA' "JUN",
    COUNT(DECODE(SUBSTR(BIRTHDAY, 4, 2), '07', 0)) || 'EA' "JUL",
    COUNT(DECODE(SUBSTR(BIRTHDAY, 4, 2), '08', 0)) || 'EA' "AUG",
    COUNT(DECODE(SUBSTR(BIRTHDAY, 4, 2), '09', 0)) || 'EA' "SEP",
    COUNT(DECODE(SUBSTR(BIRTHDAY, 4, 2), '10', 0)) || 'EA' "OCT",
    COUNT(DECODE(SUBSTR(BIRTHDAY, 4, 2), '11', 0)) || 'EA' "NOV",
    COUNT(DECODE(SUBSTR(BIRTHDAY, 4, 2), '12', 0)) || 'EA' "DEC"
FROM STUDENT;

-- 3장 연습문제 2번 응용
SELECT 
    COUNT(*) || 'EA' AS "TOTAL",
    COUNT(CASE WHEN SUBSTR(BIRTHDAY, 4, 2) = '01' THEN 0 END) || 'EA' "JAN",
    COUNT(CASE WHEN SUBSTR(BIRTHDAY, 4, 2) = '02' THEN 0 END) || 'EA' "FEB",
    COUNT(CASE WHEN SUBSTR(BIRTHDAY, 4, 2) = '03' THEN 0 END) || 'EA' "MAR",
    COUNT(CASE WHEN SUBSTR(BIRTHDAY, 4, 2) = '04' THEN 0 END) || 'EA' "APR",
    COUNT(CASE WHEN SUBSTR(BIRTHDAY, 4, 2) = '05' THEN 0 END) || 'EA' "MAY",
    COUNT(CASE WHEN SUBSTR(BIRTHDAY, 4, 2) = '06' THEN 0 END) || 'EA' "JUN",
    COUNT(CASE WHEN SUBSTR(BIRTHDAY, 4, 2) = '07' THEN 0 END) || 'EA' "JUL",
    COUNT(CASE WHEN SUBSTR(BIRTHDAY, 4, 2) = '08' THEN 0 END) || 'EA' "AUG",
    COUNT(CASE WHEN SUBSTR(BIRTHDAY, 4, 2) = '09' THEN 0 END) || 'EA' "SEP",
    COUNT(CASE WHEN SUBSTR(BIRTHDAY, 4, 2) = '10' THEN 0 END) || 'EA' "OCT",
    COUNT(CASE WHEN SUBSTR(BIRTHDAY, 4, 2) = '11' THEN 0 END) || 'EA' "NOV",
    COUNT(CASE WHEN SUBSTR(BIRTHDAY, 4, 2) = '12' THEN 0 END) || 'EA' "DEC"
FROM STUDENT;

-- 3장 연습문제 2번 - PIVOT 함수
SELECT *
FROM (
    SELECT TO_CHAR(BIRTHDAY, 'MM') AS MONTH, COUNT(*) AS COUNT
    FROM STUDENT
    GROUP BY TO_CHAR(BIRTHDAY, 'MM')
)
PIVOT (
    SUM(COUNT)
    FOR MONTH IN ('01' AS JAN, '02' AS FEB, '03' AS MAR, '04' AS APR, '05' AS MAY, '06' AS JUN,
                  '07' AS JUL, '08' AS AUG, '09' AS SEP, '10' AS OCT, '11' AS NOV, '12' AS DEC)
);

-- 3장 연습문제 3번
SELECT COUNT(STUDNO) "TOTAL",
    COUNT(DECODE(SUBSTR(TEL, 1, INSTR(TEL, ')')-1), '02', 0)) "SEOUL",
    COUNT(DECODE(SUBSTR(TEL, 1, INSTR(TEL, ')')-1), '031', 0)) "GYEONGGI",
    COUNT(DECODE(SUBSTR(TEL, 1, INSTR(TEL, ')')-1), '051', 0)) "BUSAN",
    COUNT(DECODE(SUBSTR(TEL, 1, INSTR(TEL, ')')-1), '052', 0)) "ULSAN",
    COUNT(DECODE(SUBSTR(TEL, 1, INSTR(TEL, ')')-1), '053', 0)) "DAEGU",
    COUNT(DECODE(SUBSTR(TEL, 1, INSTR(TEL, ')')-1), '055', 0)) "GYEONGNAM"
FROM STUDENT;

SELECT *
FROM (
    SELECT COUNT(STUDNO) AS COUNT,
           SUBSTR(TEL, 1, INSTR(TEL, ')') - 1) AS PREFIX
    FROM STUDENT
    GROUP BY SUBSTR(TEL, 1, INSTR(TEL, ')') - 1)
)
PIVOT (
    SUM(COUNT)
    FOR PREFIX IN ('02' AS SEOUL, '031' AS GYEONGGI, '051' AS BUSAN, '052' AS ULSAN, '053' AS DAEGU, '055' AS GYEONGNAM)
);

-- 3장 연습문제 4번
/*
INSERT INTO EMP(EMPNO, DEPTNO, ENAME, SAL) VALUES (1000, 10, 'Tiger', 3600);
INSERT INTO EMP(EMPNO, DEPTNO, ENAME, SAL) VALUES (2000, 10, 'Cat', 3000);
COMMIT;
*/

SELECT EMPNO, ENAME, JOB, SAL FROM EMP;

SELECT DEPTNO,
    SUM(DECODE(JOB, 'CLERK', SAL, 0)) "CLERK",
    SUM(DECODE(JOB, 'MANAGER', SAL, 0)) "MANAGER",
    SUM(DECODE(JOB, 'PRESIDENT', SAL, 0)) "PRESIDENT",
    SUM(DECODE(JOB, 'ANALYST', SAL, 0)) "ANALYST",
    SUM(DECODE(JOB, 'SALESMAN', SAL, 0)) "SALESMAN",
    SUM(NVL2(JOB, SAL, 0)) "TOTAL"
FROM EMP
GROUP BY ROLLUP(DEPTNO)
ORDER BY DEPTNO;

SELECT * FROM (SELECT SAL, JOB, DEPTNO FROM EMP)
PIVOT (
    SUM(SAL) FOR JOB IN ('CLERK','MANAGER','PRESIDENT','ANALYST','SALESMAN')
)
ORDER BY DEPTNO;

-- 3장 연습문제 5번
SELECT DEPTNO, ENAME, SAL, SUM(SAL) OVER(ORDER BY SAL) "TOTAL"
FROM EMP;

-- 3장 연습문제 6번
SELECT MAX(DECODE(NAME, 'apple', PRICE)) "APPLE",
    MAX(DECODE(NAME, 'grape', PRICE)) "GRAPE",
    MAX(DECODE(NAME, 'orange', PRICE)) "ORANGE"
FROM FRUIT;

-- 3장 연습문제 7번
SELECT COUNT(STUDNO) || 'EA (' ||
    ROUND(COUNT(STUDNO)/COUNT(STUDNO)*100, 0) || '%)' "TOTAL",
    COUNT(DECODE(SUBSTR(TEL, 1, INSTR(TEL, ')')-1), '02', 0)) || 'EA (' ||
    ROUND(COUNT(DECODE(SUBSTR(TEL, 1, INSTR(TEL, ')')-1), '02', 0))/COUNT(STUDNO)*100, 0) || '%)' "SEOUL",
    COUNT(DECODE(SUBSTR(TEL, 1, INSTR(TEL, ')')-1), '031', 0)) || 'EA (' ||
    ROUND(COUNT(DECODE(SUBSTR(TEL, 1, INSTR(TEL, ')')-1), '031', 0))/COUNT(STUDNO)*100, 0) || '%)' "GYEONGGI",
    COUNT(DECODE(SUBSTR(TEL, 1, INSTR(TEL, ')')-1), '051', 0)) || 'EA (' ||
    ROUND(COUNT(DECODE(SUBSTR(TEL, 1, INSTR(TEL, ')')-1), '051', 0))/COUNT(STUDNO)*100, 0) || '%)' "BUSAN",
    COUNT(DECODE(SUBSTR(TEL, 1, INSTR(TEL, ')')-1), '052', 0)) || 'EA (' ||
    ROUND(COUNT(DECODE(SUBSTR(TEL, 1, INSTR(TEL, ')')-1), '052', 0))/COUNT(STUDNO)*100, 0) || '%)' "ULSAN",
    COUNT(DECODE(SUBSTR(TEL, 1, INSTR(TEL, ')')-1), '053', 0)) || 'EA (' ||
    ROUND(COUNT(DECODE(SUBSTR(TEL, 1, INSTR(TEL, ')')-1), '053', 0))/COUNT(STUDNO)*100, 0) || '%)' "DAEGU",
    COUNT(DECODE(SUBSTR(TEL, 1, INSTR(TEL, ')')-1), '055', 0)) || 'EA (' ||
    ROUND(COUNT(DECODE(SUBSTR(TEL, 1, INSTR(TEL, ')')-1), '055', 0))/COUNT(STUDNO)*100, 0) || '%)' "GYEONGNAM"
FROM STUDENT;

-- 3장 연습문제 8번
SELECT DEPTNO, ENAME, SAL, SUM(SAL) OVER(PARTITION BY DEPTNO ORDER BY SAL) "TOTAL"
FROM EMP
ORDER BY DEPTNO;

-- 3장 연습문제 8번 응용
SELECT DEPTNO, ENAME, SAL, TO_CHAR(SUM(SAL) OVER(PARTITION BY DEPTNO ORDER BY SAL), 'L99,999') "TOTAL"
FROM EMP
ORDER BY DEPTNO;

-- 3장 연습문제 9번
SELECT DEPTNO, ENAME, SAL, SUM(SAL) OVER() "TOTAL_SAL",
    ROUND(RATIO_TO_REPORT(SAL) OVER()*100, 2) "%"
FROM EMP
ORDER BY 5 DESC, 1 ASC;

SELECT DEPTNO, ENAME, SAL, SUM(SUM(SAL)) OVER() "TOTAL_SAL",
    ROUND(RATIO_TO_REPORT(SUM(SAL)) OVER()*100, 2) "%"
FROM EMP
GROUP BY DEPTNO, ENAME, SAL
ORDER BY 5 DESC, 1 ASC;

-- 3장 연습문제 10번
SELECT DEPTNO, ENAME, SAL, SUM(SAL) OVER(PARTITION BY DEPTNO) "SUM_DEPT",
    ROUND(RATIO_TO_REPORT(SAL) OVER(PARTITION BY DEPTNO)*100, 2) "%"
FROM EMP
ORDER BY 1, 2;

SELECT DEPTNO, ENAME, SAL, SUM(SAL) OVER(PARTITION BY DEPTNO) "SUM_DEPT",
    ROUND(RATIO_TO_REPORT(SUM(SAL)) OVER(PARTITION BY DEPTNO)*100, 2) "%"
FROM EMP
GROUP BY DEPTNO, ENAME, SAL
ORDER BY 1, 2;

-- 3장 연습문제 11번
SELECT L_DATE "대출일자", L_CODE "대출종목코드", L_QTY "대출건수", L_TOTAL "대출총액",
    SUM(L_TOTAL) OVER(ORDER BY L_DATE) "누적대출금액"
FROM LOAN
WHERE L_STORE = 1000;

-- 3장 연습문제 11번 응용
SELECT TO_CHAR(TO_DATE(L_DATE), 'YYYY"년" MM"월" DD"일" DAY') "대출일자",
    L_CODE "대출종목코드",
    L_QTY || '건' "대출건수",
    TO_CHAR(L_TOTAL, 'L99,999') "대출총액",
    TO_CHAR(SUM(L_TOTAL) OVER(ORDER BY L_DATE), 'L99,999') "누적대출금액"
FROM LOAN
WHERE L_STORE = 1000;

-- 3장 연습문제 12번
SELECT L_CODE "대출종목코드",
    L_STORE "대출지점",
    L_DATE "대출일자",
    L_QTY "대출건수",
    L_TOTAL "대출액",
    SUM(L_TOTAL) OVER(PARTITION BY L_CODE, L_STORE ORDER BY L_DATE) "누적대출금액"
FROM LOAN;

-- 3장 연습문제 13번
SELECT L_DATE "대출일자", L_CODE "대출구분코드", L_QTY "대출건수", L_TOTAL "대출총액",
    SUM(L_TOTAL) OVER(PARTITION BY L_CODE ORDER BY L_QTY) "누적대출금액"
FROM LOAN
WHERE L_STORE = 1000;

-- 3장 연습문제 14번
SELECT DEPTNO, NAME, PAY, SUM(PAY) OVER() "TOTAL PAY",
    ROUND(RATIO_TO_REPORT(PAY) OVER()*100, 2) "RATIO %"
FROM PROFESSOR
ORDER BY PAY DESC;

-- 3장 연습문제 14번 응용
SELECT DEPTNO, NAME, PAY,
    DECODE(BONUS, NULL, LPAD('X', 7, ' '), LPAD('O', 7, ' ')) "BONUS 여부",
    TO_CHAR(SUM(PAY) OVER(PARTITION BY DEPTNO), 'L99,999') "TOTAL_DEPTNO",
    ROUND(RATIO_TO_REPORT(PAY) OVER(PARTITION BY DEPTNO)*100, 2) "DEPTNO_RATIO %",
    TO_CHAR(SUM(PAY) OVER(), 'L99,999') "TOTAL_PAY",
    ROUND(RATIO_TO_REPORT(PAY) OVER()*100, 2) "RATIO %"
FROM PROFESSOR
ORDER BY 1, 3 DESC;

-- 3장 연습문제 15번
SELECT DEPTNO, NAME, PAY, SUM(PAY) OVER(PARTITION BY DEPTNO) "TOTAL_DEPTNO",
    ROUND(RATIO_TO_REPORT(PAY) OVER(PARTITION BY DEPTNO)*100, 2) "RATIO(%)"
FROM PROFESSOR
ORDER BY 1, 2;

SELECT DEPTNO, NAME, PAY, SUM(PAY) OVER(PARTITION BY DEPTNO) "TOTAL_DEPTNO",
    ROUND(RATIO_TO_REPORT(SUM(PAY)) OVER(PARTITION BY DEPTNO)*100, 2) "RATIO(%)"
FROM PROFESSOR
GROUP BY DEPTNO, NAME, PAY;
