-- 4장 연습문제 1번
SELECT S.NAME "STU_NAME", S.DEPTNO1 "DEPTNO1", D.DNAME "DEPT_NAME"
FROM STUDENT S, DEPARTMENT D
WHERE S.DEPTNO1 = D.DEPTNO
ORDER BY 2, 1;

SELECT S.NAME "STU_NAME", S.DEPTNO1 "DEPTNO1", D.DNAME "DEPT_NAME"
FROM STUDENT S JOIN DEPARTMENT D
ON S.DEPTNO1 = D.DEPTNO
ORDER BY 2, 1;

-- 4장 연습문제 2번
SELECT E.NAME "NAME",
    E.POSITION "POSITION",
    TO_CHAR(E.PAY, '999,999,999') "PAY",
    TO_CHAR(P.S_PAY, '999,999,999') "Low PAY",
    TO_CHAR(P.E_PAY, '999,999,999') "High PAY"
FROM EMP2 E, P_GRADE P
WHERE E.PAY BETWEEN P.S_PAY AND P.E_PAY AND E.POSITION IS NOT NULL
ORDER BY 1;

SELECT E.NAME "NAME",
    E.POSITION "POSITION",
    TO_CHAR(E.PAY, '999,999,999') "PAY",
    TO_CHAR(P.S_PAY, '999,999,999') "Low PAY",
    TO_CHAR(P.E_PAY, '999,999,999') "High PAY"
FROM EMP2 E JOIN P_GRADE P
ON E.PAY BETWEEN P.S_PAY AND P.E_PAY
WHERE E.POSITION IS NOT NULL
ORDER BY 1;

-- 4장 연습문제 3번
SELECT E.NAME "NAME",
    TRUNC(MONTHS_BETWEEN(SYSDATE, E.BIRTHDAY)/12) "AGE",
    E.POSITION "CURR_POSITION",
    P.POSITION "BE_POSITION"
FROM EMP2 E, P_GRADE P
WHERE TRUNC(MONTHS_BETWEEN(SYSDATE, E.BIRTHDAY)/12) BETWEEN P.S_AGE(+) AND P.E_AGE(+)
ORDER BY 2, 1;

SELECT E.NAME "NAME",
    TRUNC(MONTHS_BETWEEN(SYSDATE, E.BIRTHDAY)/12) "AGE",
    E.POSITION "CURR_POSITION",
    P.POSITION "BE_POSITION"
FROM EMP2 E LEFT OUTER JOIN P_GRADE P
ON TRUNC(MONTHS_BETWEEN(SYSDATE, E.BIRTHDAY)/12) BETWEEN P.S_AGE AND P.E_AGE
ORDER BY 2, 1;

-- 4장 연습문제 4번
SELECT C.GNAME "CUST_NAME", C.POINT "POINT", 'Notebook' "GIFT_NAME"
FROM CUSTOMER C, GIFT G
WHERE C.POINT BETWEEN G.G_START AND G.G_END
    AND C.POINT >= (SELECT G_START FROM GIFT WHERE GNAME = 'Notebook')
ORDER BY 2 DESC;

SELECT C.GNAME "CUST_NAME", C.POINT "POINT", 'Notebook' "GIFT_NAME"
FROM CUSTOMER C JOIN GIFT G
ON C.POINT BETWEEN G.G_START AND G.G_END
WHERE C.POINT >= (SELECT G_START FROM GIFT WHERE GNAME = 'Notebook')
ORDER BY 2 DESC;

SELECT C.GNAME "CUST_NAME", C.POINT "POINT", G.GNAME "GIFT_NAME"
FROM CUSTOMER C, GIFT G
WHERE G.GNAME = 'Notebook' AND C.POINT >= G.G_START
ORDER BY 2 DESC;

SELECT C.GNAME "CUST_NAME", C.POINT "POINT", G.GNAME "GIFT_NAME"
FROM CUSTOMER C JOIN GIFT G
ON G.GNAME = 'Notebook' AND C.POINT >= G.G_START
ORDER BY 2 DESC;

-- 4장 연습문제 5번
SELECT A.PROFNO "PROFNO", A.NAME "NAME", TO_CHAR(A.HIREDATE, 'YYYY/MM/DD') "HIREDATE",
    COUNT(NVL2(B.PROFNO, A.PROFNO, NULL)) "COUNT"
FROM PROFESSOR A, PROFESSOR B
WHERE A.HIREDATE > B.HIREDATE(+)
GROUP BY A.PROFNO, A.NAME, A.HIREDATE
ORDER BY 4;

SELECT A.PROFNO "PROFNO", A.NAME "NAME", TO_CHAR(A.HIREDATE, 'YYYY/MM/DD') "HIREDATE",
    COUNT(NVL2(B.PROFNO, A.PROFNO, NULL)) "COUNT"
FROM PROFESSOR A LEFT OUTER JOIN PROFESSOR B
ON A.HIREDATE > B.HIREDATE
GROUP BY A.PROFNO, A.NAME, A.HIREDATE
ORDER BY 4;

-- 4장 연습문제 6번
SELECT A.EMPNO "EMPNO", A.ENAME "ENAME", A.HIREDATE "HIREDATE", COUNT(B.EMPNO) "COUNT"
FROM EMP A, EMP B
WHERE A.HIREDATE > B.HIREDATE(+)
GROUP BY A.EMPNO, A.ENAME, A.HIREDATE
ORDER BY 4;

SELECT A.EMPNO "EMPNO", A.ENAME "ENAME", A.HIREDATE "HIREDATE", COUNT(B.EMPNO) "COUNT"
FROM EMP A LEFT OUTER JOIN EMP B
ON A.HIREDATE > B.HIREDATE
GROUP BY A.EMPNO, A.ENAME, A.HIREDATE
ORDER BY 4;
