-- 5장 연습문제 1번
CREATE TABLE new_emp (
    NO NUMBER(5),
    NAME VARCHAR2(20),
    HIREDATE DATE,
    BONUS NUMBER(6,2)
);

-- 테이블이 정상적으로 생성되었는지 확인하기.
DESC NEW_EMP;

-- 5장 연습문제 2번
CREATE TABLE new_emp2
AS SELECT NO, NAME, HIREDATE FROM NEW_EMP;

-- 테이블이 정상적으로 생성되었는지 확인하기.
DESC NEW_EMP2;

-- 5장 연습문제 3번
CREATE TABLE new_emp3
AS SELECT NO, NAME, HIREDATE FROM NEW_EMP2
WHERE 1 = 2;

-- 테이블이 정상적으로 생성되었는지 확인하기.
DESC NEW_EMP3;

-- 7장 연습문제 1번
CREATE TABLE tcons (
    NO NUMBER(5) CONSTRAINT tcons_no_pk PRIMARY KEY,
    NAME VARCHAR2(20) CONSTRAINT tcons_name_nn NOT NULL,
    JUMIN VARCHAR2(13) CONSTRAINT tcons_jumin_nn NOT NULL
        CONSTRAINT tcons_jumin_uk UNIQUE,
    AREA NUMBER(1) CONSTRAINT tcons_area_ck CHECK(AREA BETWEEN 1 AND 4),
    DEPTNO VARCHAR2(6) CONSTRAINT tcons_deptno_fk REFERENCES DEPT2(DCODE)
);

-- 테이블이 정상적으로 생성되었는지 확인하기.
DESC TCONS;

-- 7장 연습문제 2번
-- EMP2 테이블의 NAME 컬럼에 UNIQUE KEY를 설정해야 TCONS 테이블에서 이를 참조하는 외래키를 설정할 수 있다.
ALTER TABLE EMP2 ADD CONSTRAINT emp2_name_uk UNIQUE(NAME);

ALTER TABLE TCONS ADD CONSTRAINT tcons_name_fk
FOREIGN KEY(NAME) REFERENCES EMP2(NAME);

-- 9장 연습문제 2번
SELECT D.DNAME, S.MAX_HEIGHT, S.MAX_WEIGHT
FROM (SELECT DEPTNO1, MAX(HEIGHT) "MAX_HEIGHT", MAX(WEIGHT) "MAX_WEIGHT"
    FROM STUDENT
    GROUP BY DEPTNO1) S, DEPARTMENT D
WHERE S.DEPTNO1 = D.DEPTNO;

-- 9장 연습문제 3번
SELECT D.DNAME, V.MAX_HEIGHT, S.NAME, S.HEIGHT
FROM (SELECT DEPTNO1, MAX(HEIGHT) "MAX_HEIGHT"
    FROM STUDENT
    GROUP BY DEPTNO1) V, STUDENT S, DEPARTMENT D
WHERE V.DEPTNO1 = S.DEPTNO1 AND S.DEPTNO1 = D.DEPTNO AND V.MAX_HEIGHT = S.HEIGHT;

-- 9장 연습문제 4번
SELECT V.GRADE, S.NAME, S.HEIGHT, V.AVG_HEIGHT
FROM (SELECT GRADE, AVG(HEIGHT) "AVG_HEIGHT"
    FROM STUDENT
    GROUP BY GRADE) V, STUDENT S
WHERE V.GRADE = S.GRADE AND S.HEIGHT > V.AVG_HEIGHT
ORDER BY 1;

-- 9장 연습문제 4번 응용
SELECT V.GRADE || '학년' "GRADE", S.NAME,
    RANK() OVER(PARTITION BY V.GRADE ORDER BY S.HEIGHT DESC) || '등' "학년별 키 순위",
    S.HEIGHT || 'cm' "HEIGHT", V.AVG_HEIGHT || 'cm' "AVG_HEIGHT"
FROM (SELECT GRADE, AVG(HEIGHT) "AVG_HEIGHT"
    FROM STUDENT
    GROUP BY GRADE) V, STUDENT S
WHERE V.GRADE = S.GRADE AND S.HEIGHT > V.AVG_HEIGHT
ORDER BY 1;

-- 9장 연습문제 5번
SELECT ROWNUM "Ranking", NAME, PAY
FROM (SELECT NAME, PAY
    FROM PROFESSOR
    ORDER BY PAY DESC)
WHERE ROWNUM BETWEEN 1 AND 5;

SELECT V.RANKING "Ranking", P.NAME, P.PAY
FROM (SELECT RANK() OVER(ORDER BY PAY DESC) "RANKING", NAME, PAY
    FROM PROFESSOR) V, PROFESSOR P
WHERE V.PAY = P.PAY AND V.RANKING BETWEEN 1 AND 5
ORDER BY 1;

-- 9장 연습문제 6번
SELECT ROWNUM "NUM", PROFNO, NAME, PAY, SUM(PAY), ROUND(AVG(PAY), 1)
FROM PROFESSOR
GROUP BY CEIL(ROWNUM/3), ROLLUP((PROFNO, NAME, PAY, ROWNUM))
ORDER BY CEIL(ROWNUM/3);

SELECT ROWNUM "NUM", PROFNO, NAME, PAY, SUM(PAY), ROUND(AVG(PAY), 1)
FROM PROFESSOR
GROUP BY ROLLUP(CEIL(ROWNUM/3), (PROFNO, NAME, PAY, ROWNUM))
ORDER BY CEIL(ROWNUM/3);
