-- 12장 계층형 쿼리 - 예제 실습
SELECT LPAD(' ', 2*(LEVEL-1)) || ENAME "ENAME",
    SYS_CONNECT_BY_PATH(ENAME, '->')
FROM EMP
START WITH MGR IS NULL
CONNECT BY PRIOR EMPNO = MGR
ORDER SIBLINGS BY EMPNO;

-- 12장 연습문제 - 계층 구조 참고
SELECT E.NAME, SYS_CONNECT_BY_PATH(E.NAME, '->') "Tree Path"
FROM EMP2 E, DEPT2 D
WHERE E.DEPTNO = D.DCODE
START WITH E.PEMPNO IS NULL
CONNECT BY PRIOR E.EMPNO = E.PEMPNO
ORDER SIBLINGS BY E.NAME;

-- 12장 연습문제 1번
SELECT LPAD(E.NAME || '-' || D.DNAME || '-' || NVL(E.POSITION, 'Team-Worker'), LEVEL*27, '-') "Name And Position"
FROM EMP2 E, DEPT2 D
WHERE E.DEPTNO = D.DCODE
START WITH E.PEMPNO IS NULL
CONNECT BY PRIOR E.EMPNO = E.PEMPNO
ORDER SIBLINGS BY E.NAME;

-- 12장 연습문제 2번
SELECT LPAD(E.NAME || '-' || D.DNAME || '-' || NVL(E.POSITION, 'Team-Worker'), LEVEL*27, '-') "Name And Position"
FROM EMP2 E, DEPT2 D
WHERE E.DEPTNO = D.DCODE
START WITH E.EMPNO = (SELECT EMPNO FROM EMP2 WHERE NAME = 'Kevin Bacon')
CONNECT BY PRIOR E.EMPNO = E.PEMPNO;

-- 12장 연습문제 3번
SELECT LPAD(E.NAME || '-' || D.DNAME || '-' || NVL(E.POSITION, 'Team-Worker'), LEVEL*27, '-') "Name And Position"
FROM EMP2 E, DEPT2 D
WHERE E.DEPTNO = D.DCODE
START WITH E.EMPNO = (SELECT EMPNO FROM EMP2 WHERE NAME = 'Kevin Costner')
CONNECT BY E.EMPNO = PRIOR E.PEMPNO;
